### ISSUE TITLE
gcc and binutils version

### ISSUE THREAD

**Issue by ghost** [noname22/megadrive-gcc#1]
Hello,
Thanks for the effort to create this script. The programs versions that the script download can be changed for more recent ones?

**Comment by noname22** [comment]
Wow, sorry. I never saw this issue. If you're still interested, the answer is yes. You can edit the .sh file and at the very top you can specify what versions you want it to download. No guarantees that it'll work though.

What I use is what's in the script right now, which is gcc 4.9.1, and it seems to work.
